# Generated by Django 4.0.4 on 2022-04-26 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('bought', models.DateField()),
                ('size', models.CharField(choices=[('11', 'Size 11'), ('10', 'Size 10'), ('9', 'Size 9'), ('8', 'Size 8'), ('7', 'Size 7')], default='11', max_length=2)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sneaker')),
            ],
        ),
    ]
