# Generated by Django 4.0.4 on 2022-04-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_laces_alter_buyer_options_alter_buyer_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='laces',
            field=models.ManyToManyField(to='main_app.laces'),
        ),
    ]
