# Generated by Django 4.0.4 on 2022-04-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_sneaker_laces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laces',
            old_name='size',
            new_name='sizes',
        ),
    ]
